export default {
  "audio-to-video": "Audio-to-Video",
  "audio-to-video-price": "Audio-to-Video Price Calculation",
  "image-to-video": "Image-to-Video",
  "image-to-video-price": "Image-to-Video Price Calculation",
  "text-to-embedding": "Text-to-Embedding",
  "text-to-embedding-price": "Text-to-Embedding Price Calculation",
  "text-to-image": "Text-to-Image",
  "text-to-image-price": "Text-to-Image Price Calculation",
  "text-to-music": "Text-to-Music",
  "text-to-music-price": "Text-to-Music Price Calculation",
  "text-to-speech": "Text-to-Speech (TTS)",
  "text-to-speech-price": "Text-to-Speech Price Calculation",
  "text-to-video": "Text-to-Video",
  "text-to-video-price": "Text-to-Video Price Calculation",
}
