name = "dryapi-automation-workflows"
main = "src/worker.ts"
compatibility_date = "2026-03-11"
workers_dev = true

placement = { region = "aws:us-west-1"}

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true


[triggers]
crons = ["0 * * * *"]

[[workflows]]
name = "dryapi-automation-workflow"
binding = "AUTOMATION_WORKFLOW"
class_name = "AutomationWorkflow"

[vars]
AUTOMATION_SCHEDULED_FLOWS = ""
